# Generated by Django 5.1.6 on 2026-07-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_playlist_dialog_photo_song_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
