# Generated by Django 5.1.6 on 2026-07-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_song_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=200)),
                ('asset_id', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('asset_type', models.CharField(default='image', max_length=20)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
