# Generated by Django 5.1.6 on 2026-08-02 10:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_galleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedUpload',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(db_index=True, max_length=200)),
                ('device_id', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=255)),
                ('total_size', models.BigIntegerField()),
                ('chunk_size', models.IntegerField(default=1048576)),
                ('received_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('mime_type', models.CharField(default='image/jpeg', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='image',
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='file',
            field=models.FileField(default=1, upload_to='gallery/'),
            preserve_default=False,
        ),
    ]
