# Generated by Django 5.1.6 on 2026-08-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0005_chunkedupload_remove_galleryitem_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سرور')),
                ('flag', models.CharField(default='🌐', max_length=10, verbose_name='پرچم')),
                ('url', models.TextField(verbose_name='کانفیگ URL (vless:// یا vmess://)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کانفیگ VPN',
                'verbose_name_plural': 'کانفیگ\u200cهای VPN',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
